services:
  # Local services are available on their ports, but also available on:
  # http://api.localhost.tiangolo.com: backend
  # http://dashboard.localhost.tiangolo.com: frontend
  # etc. To enable it, update .env, set:
  # DOMAIN=localhost.tiangolo.com
  proxy:
    image: traefik:3.0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "80:80"
      - "8090:8080"
    # Duplicate the command from docker-compose.yml to add --api.insecure=true
    command:
      # Enable Docker in Traefik, so that it reads labels from Docker services
      - --providers.docker
      # Add a constraint to only use services with the label for this stack
      - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
      # Do not expose all Docker services, only the ones explicitly exposed
      - --providers.docker.exposedbydefault=false
      # Create an entrypoint "http" listening on port 80
      - --entrypoints.http.address=:80
      # Create an entrypoint "https" listening on port 443
      - --entrypoints.https.address=:443
      # Enable the access log, with HTTP requests
      - --accesslog
      # Enable the Traefik log, for configurations and errors
      - --log
      # Enable debug logging for local development
      - --log.level=DEBUG
      # Enable the Dashboard and API
      - --api
      # Enable the Dashboard and API in insecure mode for local development
      - --api.insecure=true
    labels:
      # Enable Traefik for this service, to make it available in the public network
      - traefik.enable=true
      - traefik.constraint-label=traefik-public
      # Dummy https-redirect middleware that doesn't really redirect, only to
      # allow running it locally
      - traefik.http.middlewares.https-redirect.contenttype.autodetect=false
    networks:
      - traefik-public
      - default

  ssh-agent:
    build: ./ssh_agent
    environment:
      SSH_AUTH_SOCK: /ssh/agent.sock
    volumes:
      - ssh-socket:/ssh
      - ./ssh_agent/ssh_key/priv_ed25519.key:/priv_ed25519.key:ro   # Mount your SSH private key as read-only
    entrypoint: >
      sh -c "rm -f /ssh/agent.sock && ssh-agent -a /ssh/agent.sock &&
             ssh-add /priv_ed25519.key &&
             tail -f /dev/null"
    healthcheck:
      test: ["CMD", "ssh-add", "-l"]
      interval: 5s
      timeout: 3s
      retries: 3

  db:
    restart: "no"
    ports:
      - "5432:5432"

  adminer:
    restart: "no"
    ports:
      - "8080:8080"

  backend:
    restart: "no"
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
      - 4.4.4.4
    build:
      context: ./backend
    # command: sleep infinity  # Infinite loop to keep container alive doing nothing
    command: sh -c "python app/create_ssh_config.py && fastapi run --reload 'app/main.py'"
    develop:
      watch:
        - path: ./backend
          action: sync
          target: /app
          ignore:
            - ./backend/.venv
            - .venv
        - path: ./backend/pyproject.toml
          action: rebuild
    # TODO: remove once coverage is done locally
    volumes:
      - ./backend/htmlcov:/app/htmlcov
      - ssh-socket:/ssh
      - ./test_token_key/:/app/test_token_key/
    environment:
      SMTP_HOST: "mailcatcher"
      SMTP_PORT: "1025"
      SMTP_TLS: "false"
      EMAILS_FROM_EMAIL: "noreply@example.com"
      SSH_AUTH_SOCK: /ssh/agent.sock



  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  frontend:
    restart: "no"
    ports:
      - "5173:80"
    build:
      context: ./frontend
      target: build-stage
      args:
        - VITE_API_URL=${BACKEND_HOST?Variable not set}
        - NODE_ENV=development
    env_file:
      - .env
    environment:
       - VITE_API_URL=${BACKEND_HOST?Variable not set}
    command: ["sh", "-c", "CHOKIDAR_USEPOLLING=1 npm run dev -- --host 0.0.0.0 --port 80"]
    volumes:
      - ./frontend:/app
      - /app/node_modules


networks:
  traefik-public:
    # For local dev, don't expect an external Traefik network
    external: false
